// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvB5lJkJJ_aWt2TJkar4H8BW15SBTe9b4',
    appId: '1:814567343597:web:b7dc6913fd5a7164d953e4',
    messagingSenderId: '814567343597',
    projectId: 'mds-project-349316',
    authDomain: 'mds-project-349316.firebaseapp.com',
    storageBucket: 'mds-project-349316.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTiew0sotIIOY8VMxUxdg32has8totNaQ',
    appId: '1:814567343597:android:0851e2097b858f06d953e4',
    messagingSenderId: '814567343597',
    projectId: 'mds-project-349316',
    storageBucket: 'mds-project-349316.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANV42d2WDDmwlqaDh4AM8UKVR88PuEXOc',
    appId: '1:814567343597:ios:fdd0e6c568fdf3a2d953e4',
    messagingSenderId: '814567343597',
    projectId: 'mds-project-349316',
    storageBucket: 'mds-project-349316.appspot.com',
    iosClientId: '814567343597-oidvkb4p7hhac313lnb71snur42bbui9.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );
}
